# Generated by Django 5.2.8 on 2025-11-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0002_booking_guests_booking_status_listing_max_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guests',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
